### ISSUE TITLE
Draven doesnt catch axes

### ISSUE THREAD

**Issue by emrexus** [NightMoon032/AimTec#2]
Draven doesnt catch his axes for three weeks, its a big problem. Please fix it. :(

**Comment by NightMoon032** [comment]
do one thing: delect your settings
Win + R : %appdata% -> "Aimtec.SDK" -> "MenuSettings" -> find "SharpShooter"  directories and delect it
test it in custom game (all axe have circle draw)

**Comment by emrexus** [comment]
Thanks! It works good now, i will talk about it in your forum topic. Thanks again for a quick answer.
