### ISSUE TITLE
Vayne's condemn

### ISSUE THREAD

**Issue by emrexus** [NightMoon032/AimTec#3]
Her condemn isn't working smooth. It tries to condemn randomly, not an antigapcloser i'm sure. And, her harass isn't working too. she isnt use her q, (i tried to turn on harass key, still same) 

Check her condemn, its unplayable. And by the way, I tried to delete Sharpshooter file and reinstalled it, it didn't work.

**Comment by NightMoon032** [comment]
will be check

**Comment by NightMoon032** [comment]
now update it (should be fix)
and the harass q logic (only work for after attack)

**Comment by emrexus** [comment]
thanks
